title: "Customer Segmentation with KMeans Clustering"
theme: jekyll-theme-minimal

description: >
  A short description of your project

kramdown:
  input: GFM
  math_engine: mathjax # you can also set this field to 'katex'
    
