title: My Project
description: > 
  A short description of your project

# Use Jekyll's built-in kramdown engine
# which can handle math with the right settings
markdown: kramdown

kramdown:
  input: GFM            # GitHub Flavored Markdown
  math_engine: mathjax  # Render math using MathJax
  math_engine_opts:
    # Load MathJax from a CDN (JSDelivr, UNPKG, Cloudflare, etc.)
    server: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
